layout_spectrum: 0.2150538
typography_spectrum: 0.5125448
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.8924731
  brandColors:
    - '#010103'
    - '#818181'
    - '#E0DEE1'
    - '#A9B6C6'
    - '#535154'
  rhythmicContrast: 1
name: 'BB Love '
